WebApplication1/Models/Card.cs
using System.Numerics;

namespace WebApplication1.Models
{
    public class Card
    {
        public int Id { get; set; }
        public string? photo { get; set; }
        public string? Bank { get; set; }
        public string? emisor { get; set; }
        public  string? owner {  get; set; }
        public string? cardnumber { get; set; }
        public int? cvv { get; set;}
        public DateTime? DueDate { get; set;}
       
    }
    
}

WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Controllers/CardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;
using WebApplication1.Models;
using m = WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CardController : Controller
    {
        // GET: CardController
        [HttpPost]
        public  ActionResult Create(string photo, string bank, string emisor, string owner, string cardnumber, int cvv, DateTime duedate)
        {
            List<SqlParameter> param = new List<SqlParameter>()
            {
                new SqlParameter("@photo","../img/"+photo),
                new SqlParameter("@bank",bank),
                new SqlParameter("@emisor",emisor),
                new SqlParameter("@owner",owner),
                new SqlParameter("@cardnumber",cardnumber),
                new SqlParameter("@cvv",cvv),
                new SqlParameter("@duedate",duedate)

            };
            DataBaseWebHelper.DataBaseHelper.ExecuteNonQuery("spCreateCard", param);


            return RedirectToAction("Index","Home");
        }
      
        [HttpPost]
        public ActionResult Update(int id, string photo, string bank, string emisor, string owner, string cardnumber, int cvv, DateTime duedate)
        {
            List<SqlParameter> param = new List<SqlParameter>()
            {
                new SqlParameter("@ID",id),
                new SqlParameter("@photo","../img/"+photo),
                new SqlParameter("@bank",bank),
                new SqlParameter("@emisor",emisor),
                new SqlParameter("@owner",owner),
                new SqlParameter("@cardnumber",cardnumber),
                new SqlParameter("@cvv",cvv),
                new SqlParameter("@duedate",duedate)

            };
            DataBaseWebHelper.DataBaseHelper.ExecuteNonQuery("spUpdateCard", param);


            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        { 
            
            List<SqlParameter> param = new List<SqlParameter>()
            {
                new SqlParameter("id",Id)
            };

            DataBaseWebHelper.DataBaseHelper.ExecuteNonQuery("spDeleteCard", param);
            return RedirectToAction("Index", "Home");
        }

    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using WebApplication1.Models;


namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {   
            ViewBag.Cardlist = GetCards();
            return View();
        }
        public List<Card> GetCards()
        {
         
            Card card = new Card();
            List<Card> CardList = new List<Card>();
            DataTable ds = DataBaseWebHelper.DataBaseHelper.ExecuteQuery("spGetCards", null);

            DateTime? fechavencimiento = card.DueDate;
            DateTime fechaaviso = DateTime.Today;
            
            foreach (DataRow dr in ds.Rows)
            {
                CardList.Add(new Card
                {
                    Id = Convert.ToInt32(dr["ID"]),
                    photo = dr["photo"].ToString(),
                    Bank = dr["bank"].ToString(),
                    emisor = dr["emisor"].ToString(),
                    owner = dr["owner"].ToString(),
                    cardnumber = (dr["cardnumber"]).ToString(),
                    cvv = Convert.ToInt32(dr["cvv"]),
                    DueDate = Convert.ToDateTime(dr["DueDate"])
                });
            }

            return CardList;
        }
        public IActionResult CreateCard()
        {
            return View();
        }
        public List<Card> GetCard(int Id)
        {
            //Aqui nos traemos los Resorts de SQL Server
            List<Card> CardList = new List<Card>();
            List<SqlParameter> param = new List<SqlParameter>() { new SqlParameter("@Id",Id)};
            DataTable ds = DataBaseWebHelper.DataBaseHelper.ExecuteQuery("spGetCard", param);
            //

            //Recorremos el objeto para crear la lista de Resorts
            foreach (DataRow dr in ds.Rows)
            {
                CardList.Add(new Card
                {
                    Id = Convert.ToInt32(dr["ID"]),
                    photo = dr["photo"].ToString(),
                    Bank = dr["bank"].ToString(),
                    emisor = dr["emisor"].ToString(),
                    owner = dr["owner"].ToString(),
                    cardnumber = (dr["cardnumber"]).ToString(),
                    cvv = Convert.ToInt32(dr["cvv"]),
                    DueDate = Convert.ToDateTime(dr["DueDate"])
                });
            }
            return CardList;

            
        }
        public IActionResult UpdateCard(int Id) 
        {  
            ViewBag.Update = GetCard(Id);
            return View(); 
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Views/Home/CreateCard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<html>
<head>
    <title>Formulario de Creación de Tarjeta</title>
    <!-- Enlaza la hoja de estilos de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Crear Nueva Tarjeta</h1>
        <form action="@Url.Action("Create","Card")" method="POST">
            <div class="form-group">
                <label for="nombre">Nombre del Titular de la Tarjeta:</label>
                <input type="text" class="form-control" id="owner" name="owner" required>
            </div>
            <div class="form-group">
                <label for="nombre">Banco:</label>
                <input type="text" class="form-control" id="back" name="bank" required>
            </div>
            <div class="form-group">
                <label for="nombre">Emisor:</label>
                <input type="text" class="form-control" id="Emisor" name="Emisor" required>
            </div>
            <div class="form-group">
                <label for="nombre">Foto:</label>
                <input type="file" class="form-control" id="photo" name="photo" required>
            </div>
            <div class="form-group">
                <label for="numero">Número de Tarjeta:</label>
                <input type="text" class="form-control" id="cardnumber" name="cardnumber" required>
            </div>
            <div class="form-group">
                <label for="vencimiento">Fecha de Vencimiento (MM/DD/YY):</label>
                <input type="text" class="form-control" id="duedate" name="duedate" required>
            </div>
            <div class="form-group">
                <label for="cvv">CVV:</label>
                <input type="text" class="form-control" id="cvv" name="cvv" required>
            </div>
            <button type="submit" class="btn btn-primary">Crear Tarjeta</button>
        </form>
    </div>

    <!-- Incluye jQuery y la biblioteca de Bootstrap (JS) si es necesario -->
</body>
</html>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body{
           
            margin: 0; 
            padding: 0; 
        }
        .card:hover {
            transform: scale(1.05);
            transition: transform 0.3s;
        }

        .card {
            position: relative;
            overflow: hidden;
        }

            .card .card-img-overlay {
                background: rgba(0, 0, 0, 0.6);
                color: white;
                position: absolute;
                top: 0;
                right: 0;
                width: 100%;
                height: 100%;
                padding: 2%; 
                box-sizing: border-box; 
            }

            .card .card-img-overlay .card-title{
                    font-size: 3vw;
                    position: absolute;
                    right: 5%;
                    color: white;
                    transition: all 0.3s;
                    bottom: 40%
            }

            .card .card-img-overlay .card-emisor {
                    font-size: 3vw;
                    position: absolute;
                    right:10%;
                    transition: all 0.3s;
                    bottom: 5%
            }

            .card .card-img-overlay .card-cardnumber {
                    font-size: 3vw;
                    position: absolute;
                    right: 14%;
                    transition: all 0.3s;
                    bottom: 20%;
                    letter-spacing:2px;
            }

            .card .card-img-overlay .card-cvv {
                    font-size: 3vw;
                    position: absolute;
                    right: 40%;
                    transition: all 0.3s;
                    bottom: 5%
            }

        .button {
            background-color: #007BFF;
            color: #fff;
            width: 20%;
            height: 2%;
            font-size: 100%;
            padding: 4px 10px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 150%;
            transition: background-color 0.3s, transform 0.3s;
        }

        .button:hover {
                background-color: #2980b9;
                transform: scale(1.1);
            }


            
        .card-img-overlay.disabled {
                opacity: 0.2;
        }

        .estiloBoton {
            background-color: #007BFF;
            color: #fff;
            width: 20%;
            height: 2%;
            font-size: 100%;
            padding: 0.4% 2%;
            border: none;
            border-radius: 5%;
            cursor: pointer;
            
        }

            .estiloBoton:hover {
                background-color: #0056b3;
            }

        .DeleteButtom {
            background-color: red;
            color: #fff;
            width: 20%;
            height: 2%;
            font-size: 100%;
            padding: 0.4% 2%;
            border: none;
            border-radius: 5%;
            cursor: pointer;
            
        }

            .DeleteButtom:hover {
                box-shadow: inset 0 0 0 50px #E86A6A;
            }
        .UpdateButtom{
            background-color: orange;
            color: #fff;
            width: 20%;
            height: 2%;
            font-size: 100%;
            padding: 0.4% 2%;
            border: none;
            border-radius: 5%;
            cursor: pointer;
        }

            .UpdateButtom:hover {
                box-shadow: inset 0 0 0 50px #E7AC3D;
            }

        
        .customTooltipButton
        {   
            width: 20%;
            height: 2%;
            font-size: 100%;
            padding: 0.4% 2%;
            border: none;
            border-radius: 5%;
            cursor: pointer;
        }
      
    </style>
</head>
<body>
    <h1 class="title"> Mis tarjetas </h1>
    <br>
    <a asp-action="CreateCard" asp-controller="Home" class="button">Agregar tarjeta</a>
    <br>
    <br>
  

   @foreach (var card in ViewBag.Cardlist)
    { 
 
          
                <input type="hidden" class="due-date" value="@card.DueDate">
            <button class="estiloBoton" id="toggleButton">Habilitar / Deshabilitar</button>
            <form method="post" action="@Url.Action("Delete","Card")">
                <button class="DeleteButtom" type="submit">Eliminar tarjeta</button>
                <input type="hidden" name="Id" id="Id" value="@card.Id">
            </form>
            <form method="post" action="@Url.Action("UpdateCard","Home")">
                <button class="UpdateButtom" type="submit">Editar tarjeta</button>
                <input type="hidden" name="Id" id="Id" value="@card.Id">
            </form>
            
            
            <div  class="card">
                <img src="@card.photo" class="card-img-top" alt="Foto de la tarjeta" id="cardImage">
                <div class="card-img-overlay">
                    <h5 class="card-title">Titular: @card.owner</h5>
                    <p class="card-cardnumber">
                        <span id="encryptedCardNumber">@card.cardnumber</span>
                    </p>
                    <p class="card-emisor">
                        <span id="cardIssuer">@card.emisor</span>
                    </p>
                    <p class="card-cvv">CVV: <span id="cardIssuer">@card.cvv</span></p>
                    <button type="button" class="btn btn-secondary"
                            data-bs-toggle="tooltip" data-bs-placement="top"
                            data-bs-custom-class="custom-tooltip"
                            id="customTooltipButton">
                        Recodatorio de renovacion
                    </button>
                </div>
            </div>
        <br>

       

    }
    

    
        <script>
        // Inicialmente, la tarjeta está habilitada
        var tarjetaHabilitada = true;

        // Función para habilitar o deshabilitar la tarjeta
        function toggleTarjeta() {
            var cardImage = document.getElementById("cardImage");
            tarjetaHabilitada = !tarjetaHabilitada; // Cambia el estado

            if (tarjetaHabilitada) {
                // Habilitar la tarjeta
                cardImage.style.opacity = "1";
            } else {
                // Deshabilitar la tarjeta
                cardImage.style.opacity = "0.6";
            }
        }

        // Agrega un evento de clic al botón
        var toggleButton = document.getElementById("toggleButton");
        toggleButton.addEventListener("click", toggleTarjeta);

    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const cardElements = document.querySelectorAll('.wallet');
            const customTooltipButton = document.getElementById('customTooltipButton');
            cardElements.forEach(function (cardElement) {
                const dueDateElement = cardElement.querySelector('.due-date');
                const dueDateValue = new Date(dueDateElement.value);
                const today = new Date();

                // Calcula la fecha de vencimiento en 3 meses
                const threeMonthsFromNow = new Date(today);
                threeMonthsFromNow.setMonth(threeMonthsFromNow.getMonth() + 3);

                if (dueDateValue < threeMonthsFromNow) {
                    // Agrega una notificación para tarjetas próximas a vencer
                    const tooltipContent = "La tarjeta está proxima a vencer, por favor renuevala";
                    customTooltipButton.setAttribute('data-bs-title', tooltipContent);
                    new bootstrap.Tooltip(customTooltipButton);
                }
                else {
                    const tooltipContent = "La tarjeta está a dia";
                    customTooltipButton.setAttribute('data-bs-title', tooltipContent);
                    new bootstrap.Tooltip(customTooltipButton);
                }
            });
        });

    </script>
    <script>
        // Agrega un evento de carga de página para cada tarjeta
        document.addEventListener('DOMContentLoaded', function () {
            const cardNumbers = document.querySelectorAll('.card-cardnumber span');
            cardNumbers.forEach(function (cardNumber) {
                const originalCardNumber = cardNumber.textContent;
                const maskedCardNumber = maskCardNumber(originalCardNumber);
                cardNumber.textContent = maskedCardNumber;
            });
        });

        function maskCardNumber(cardNumber) {
            // Asegurarse de que la tarjeta tenga al menos 12 caracteres
            if (cardNumber.length < 12) {
                return cardNumber; // No suficientes dígitos para enmascarar
            }

            // Tomar los primeros 12 caracteres y reemplazarlos por 'X'
            const first12Digits = cardNumber.substring(0, 12);
            const maskedCardNumber = 'XXXXXXXXXXXX' + cardNumber.substring(12);

            return maskedCardNumber;
        }
    </script>
    
</body>
</html>

WebApplication1/Views/Home/UpdateCard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<html>
<head>
    <title>Formulario de Editar la Tarjeta</title>
    <!-- Enlaza la hoja de estilos de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    @foreach(var card in ViewBag.Update)
    {
        <div class="container">
            <h1 class="mt-5">Editar Tarjeta</h1>
            <form action="@Url.Action("Update","Card")" method="POST">
                <input type="hidden" name="Id" id="Id" value="@card.Id">
                <div class="form-group">
                    <label for="nombre">Nombre del Titular de la Tarjeta:</label>
                    <input type="text" class="form-control" id="owner" name="owner" value="@card.owner" required>
                </div>
                <div class="form-group">
                    <label for="nombre">Banco:</label>
                    <input type="text" class="form-control" id="back" name="bank" value="@card.Bank" required>
                </div>
                <div class="form-group">
                    <label for="nombre">Emisor:</label>
                    <input type="text" class="form-control" id="Emisor" name="Emisor" value="@card.emisor" required>
                </div>
                <div class="form-group">
                    <label for="nombre">Foto:</label>
                    <input type="file" class="form-control" id="photo" name="photo" value="@card.photo" required>
                </div>
                <div class="form-group">
                    <label for="numero">Número de Tarjeta:</label>
                    <input type="text" class="form-control" id="cardnumber" name="cardnumber" value="@card.cardnumber" required>
                </div>
                <div class="form-group">
                    <label for="vencimiento">Fecha de Vencimiento (MM/DD/YY):</label>
                    <input type="text" class="form-control" id="duedate" name="duedate" value="@card.DueDate" required>
                </div>
                <div class="form-group">
                    <label for="cvv">CVV:</label>
                    <input type="text" class="form-control" id="cvv" name="cvv" value="@card.cvv" required>
                </div>
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
            </form>
        </div>
        
    }

</body>
</html>

WebApplication1/Views/Reports/Index.cshtml
@{
    ViewData["Title"] = "Reports";
}


<p>You can see the item reports here</p> <a asp-controller="Reports" asp-action="Sales">Sales</a>

WebApplication1/Views/Reports/Sales.cshtml
@{
    ViewData["Title"] = "Reports";
}

<p> Sales Report </p> 
<img src="https://www.actitime.com/wp-content/uploads/2018/12/Reports.png"></img>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VirtualWallet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action=""></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index"></a>
                        </li>
                    </ul>


                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>



</html>